version: '3'

services:
  app:
    build:
      context: .
    volumes:
      - ./target/here-to-help-1.0-SNAPSHOT.jar:/app.jar
    ports:
      - 8080:8080
    depends_on:
      - "mysql"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306"]
      interval: 30s
      timeout: 10s
      retries: 5
    env_file:
      - api.env
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: heretohelp
    ports:
      - 3306:3306
