version: '2.1'

services:
  app:
    build:
      context: .
    volumes:
      - ./target/here-to-help-1.0-SNAPSHOT.jar:/app.jar
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - api.env
    restart: unless-stopped

  mysql:
    image: mysql:5.5.59
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: heretohelp
    ports:
      - 3306:3306
    healthcheck:
      test: "exit 0"
    restart: unless-stopped
