version: '2.1'

services:
  app:
    build:
      context: .
    volumes:
      - ./target/here-to-help-1.0-SNAPSHOT.jar:/app.jar
    ports:
      - ${JAVA_PORT}:8080
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env

  ${DATASOURCE_HOST}:
    image: mysql:5.5.59
    environment:
      MYSQL_ROOT_PASSWORD: ${DATASOURCE_PASSWORD}
      MYSQL_DATABASE: heretohelp
    ports:
      - ${DATASOURCE_PORT}:3306
    healthcheck:
      test: "exit 0"
