swagger: "2.0"
info:
  description: "This is a restful web service used to log hours for non-profits to submit for money grants."
  version: "1.0.0"
  title: ""

paths:
  /ping:
    get:
      responses:
        '200':
          description: OK

definitions:
  User:
    type: "object"
    required:
    - "user_id"
    - "first_name"
    - "last_name"
    - "email"
    - "role"
    properties:
      user_id:
        type: "string"
        format: "uuid"
      first_name:
        type: "string"
      last_name:
        type: "string"
      email:
        type: "string"
        format: "email"
      role:
        type: "string"
        description: "Order Status"
  Login_Token:
    type: "object"
    required:
    - "user_id"
    - "login_token"
    - "login_token_expiration"
    properties:
      user_id:
        type: "string"
        format: "uuid"
      login_token:
        type: "string"
      login_token_expiration:
        type: "string"
        format: "date-time"
  Organization:
    type: "object"
    required:
    - "organization_id"
    - "name"
    - "description"
    - "email"
    - "phone_number"
    properties:
      organization_id:
        type: "string"
        format: "uuid"
      name:
        type: "string"
      description:
        type: "string"
      email:
        type: "string"
        format: "email"
      phone_number:
        type: "string"
      website_url:
        type: "string"
      facebook_url:
        type: "string"
      twitter_url:
        type: "string"
      instagram_url:
        type: "string"
  User_Organization:
    type: "object"
    required:
    - "user_id"
    - "organization_id"
    properties:
      user_id:
        type: "string"
        format: "uuid"
      organization_id:
        type: "string"
        format: "uuid"
  Project:
    type: "object"
    required:
    - "project_id"
    - "name"
    - "start_date"
    - "end_date"
    properties:
      project_id:
        type: "string"
        format: "uuid"
      name:
        type: "string"
      description:
        type: "string"
      start_date:
        type: "string"
        format: "date-time"
      end_date:
        type: "string"
        format: "date-time"
  User_Project:
    type: "object"
    required:
    - "user_id"
    - "project_id"
    properties:
      user_id:
        type: "string"
        format: "uuid"
      project_id:
        type: "string"
        format: "uuid"
  Check_In:
    type: "object"
    required:
    - "user_id"
    - "project_id"
    - "time_in"
    - "time_out"
    properties:
      user_id:
        type: "string"
        format: "uuid"
      project_id:
        type: "string"
        format: "uuid"
      time_in:
        type: "string"
        format: "date-time"
      time_out:
        type: "string"
        format: "date-time"
  
